### ISSUE TITLE
Error: Cannot find module 'twig' from

### ISSUE THREAD

**Issue by roelvanhintum** [dane-harnett/twigify#5]
Browserify says `Error: Cannot find module 'twig' from` when using the following require:
`var Template = require('./test.twig');`
I double checked the paths and configured the transform in package.json. I also tried installing globally and running from the command line like the readme example.
Am i missing something obvious?

In my package.json it's configured as follows:

```
"browserify": {
    "transform": [
      "twigify"
    ]
  },
  "twigify": {
    "extensions": [
      "twig"
    ]
  },
```

browserify 10.2.1
twigify 0.0.4

**Comment by scottwarren** [comment]
Did you install Twigify as a local dependency? `npm install --save-dev twigify` is what I ran, and the `Twig` module was installed in: `<project_dir>/node_modules/twigify/node_modules/twig`.

If this doesn't solve your issue, can you please list the directory that contains your project, as well as what's inside the `node_modules` dir.

**Comment by roelvanhintum** [comment]
It turns out that twigify requires twig also to be installed in: `<project_dir>/node_modules/twig`
It was already correctly installed in `<project_dir>/node_modules/twigify/node_modules/twig`
